name: Wokwi CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run Wokwi Simulation
      uses: wokwi/wokwi-ci-action@v1
      env:
        # Aqui ele pega o Secret exato que você criou lá nas configurações do GitHub
        WOKWI_CLI_TOKEN: ${{ secrets.WOKWI_API_KEY }}
      with:
        # Ele vai rodar a placa e esperar essa frase aparecer no terminal para dar o OK
        expect_text: 'Sistema Iniciado'
        timeout: 15000