name: Wokwi CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run Wokwi Simulation
      uses: wokwi/wokwi-ci-action@v1
      env:
        WOKWI_CLI_TOKEN: ${{ secrets.WOKWI_API_KEY }}
      with:
        expect_text: 'Sistema Iniciado'
        timeout: 15000